import java.util.Scanner;

//abnormal situation occurs at runtime
//checked
//unchecked
//5.keyword
//1.try
//2.catch
//3.finally
//4.throw
//5.throws
public class ExceptionDemo {
	public static void main(String[] args) {
		try {
			Scanner sc = new Scanner(System.in);
			System.out.println("enter a = ");
			int a = sc.nextInt();
			System.out.println("enter b = ");
			int b = sc.nextInt();
			int c = a/b;
			System.out.println(c);
		} catch (Exception e) {
		}
	}
}
